# Generated by Django 4.0 on 2021-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent_rem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('rent_amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('tenent_email', models.CharField(max_length=122)),
                ('tenent_phone', models.IntegerField()),
                ('tmessage', models.TextField()),
            ],
        ),
    ]
