# Generated by Django 4.0 on 2022-01-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_rent_rem_tmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_rem',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
