# Generated by Django 4.0 on 2022-01-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rent_rem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_rem',
            name='tenent_phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
